-- Settling on a refund, rather than being told one.
--
-- A cancellation used to be answered once: the coach approved with an amount,
-- and the client's only options were to take it or have asked for nothing. That
-- is a verdict, not an agreement -- and since the money moves directly between
-- the two of them, an agreement is what it has to be.
--
-- Now either side can put a figure on the table and the other can accept it or
-- counter. One offer stands at a time, and whoever did not make it is the one
-- who can accept it.

alter table public.package_cancellations
  drop constraint if exists package_cancellations_status;
alter table public.package_cancellations
  add constraint package_cancellations_status
  check (status in ('requested', 'offered', 'approved', 'rejected', 'withdrawn'));

-- The thread, not just the latest number.
--
-- A single `offer_cents` column on the request would answer "what is on the
-- table" and nothing else. People argue about money by remembering what was
-- said, so the exchange is kept and the current offer is simply its last row.
create table if not exists public.package_refund_offers (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.package_cancellations(id) on delete cascade,
  offered_by  uuid not null references public.users(id) on delete cascade,
  amount_cents int not null check (amount_cents >= 0),
  note        text,
  created_at  timestamptz not null default now(),
  -- Ordering is by this, not by created_at. now() is the TRANSACTION's start
  -- time, identical for every row written in one transaction, so two offers
  -- could tie and "the latest offer" would be whichever the planner returned
  -- first. A sequence cannot tie.
  seq         bigint generated by default as identity
);

create index if not exists package_refund_offers_request_idx
  on public.package_refund_offers (request_id, seq desc);

alter table public.package_refund_offers enable row level security;

-- Visible to the two people arguing about it, and nobody else. The parent row
-- already says who those are.
drop policy if exists refund_offer_parties_read on public.package_refund_offers;
create policy refund_offer_parties_read on public.package_refund_offers
  for select using (
    exists (
      select 1 from package_cancellations r
       where r.id = request_id
         and (r.client_id = current_app_user() or r.coach_id = current_app_user())
    )
  );

-- No insert policy on purpose: offers go through the RPC below, because taking
-- turns is a rule a column privilege cannot express.
grant select on public.package_refund_offers to authenticated;

-- Put a figure on the table.
create or replace function public.offer_package_refund(
  p_request uuid,
  p_cents int,
  p_note text default null
)
returns table (id uuid, amount_cents int)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_me uuid := require_app_user();
  v_row package_cancellations%rowtype;
  v_last uuid;
begin
  if p_cents is null or p_cents < 0 then
    raise exception 'Offer an amount of 0 or more.';
  end if;

  select * into v_row from package_cancellations r where r.id = p_request;
  if v_row.id is null then
    raise exception 'That request no longer exists.';
  end if;
  if v_me <> v_row.client_id and v_me <> v_row.coach_id then
    raise exception 'That request is not yours.';
  end if;
  if v_row.status not in ('requested', 'offered') then
    raise exception 'That request has already been settled.';
  end if;

  -- Offering twice in a row is not negotiating, it is talking over somebody.
  -- Whoever made the standing offer waits for an answer to it.
  select o.offered_by into v_last
    from package_refund_offers o
   where o.request_id = p_request
   order by o.seq desc
   limit 1;
  if v_last = v_me then
    raise exception 'Your offer is on the table. Wait for an answer, or they can counter it.';
  end if;

  -- Aliased: `returns table (id uuid, ...)` declares an OUT parameter called
  -- `id`, so an unaliased `where id = ...` is ambiguous between that variable
  -- and the column. Postgres refuses it at runtime, not at creation, so only
  -- calling the function finds it.
  update package_cancellations r set status = 'offered' where r.id = p_request;

  return query
    insert into package_refund_offers (request_id, offered_by, amount_cents, note)
    values (p_request, v_me, p_cents, nullif(btrim(coalesce(p_note, '')), ''))
    returning package_refund_offers.id, package_refund_offers.amount_cents;
end $function$;

revoke execute on function public.offer_package_refund(uuid, int, text) from public, anon;
grant execute on function public.offer_package_refund(uuid, int, text) to authenticated;

-- Take the standing offer.
--
-- Only the side that did not make it: accepting your own offer would be
-- approving your own refund, which is the whole thing this is meant to prevent.
create or replace function public.accept_package_refund(p_request uuid)
returns table (id uuid, status text, refund_cents int)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_me uuid := require_app_user();
  v_row package_cancellations%rowtype;
  v_offer package_refund_offers%rowtype;
begin
  select * into v_row from package_cancellations r where r.id = p_request;
  if v_row.id is null then
    raise exception 'That request no longer exists.';
  end if;
  if v_me <> v_row.client_id and v_me <> v_row.coach_id then
    raise exception 'That request is not yours.';
  end if;
  if v_row.status <> 'offered' then
    raise exception 'There is no offer to accept yet.';
  end if;

  select * into v_offer
    from package_refund_offers o
   where o.request_id = p_request
   order by o.seq desc
   limit 1;
  if v_offer.id is null then
    raise exception 'There is no offer to accept yet.';
  end if;
  if v_offer.offered_by = v_me then
    raise exception 'That is your own offer. They accept it, or counter.';
  end if;

  return query
    update package_cancellations r
       set status = 'approved',
           refund_cents = v_offer.amount_cents,
           decided_by = v_me,
           decided_at = now()
     where r.id = p_request
    returning r.id, r.status, r.refund_cents;
end $function$;

revoke execute on function public.accept_package_refund(uuid) from public, anon;
grant execute on function public.accept_package_refund(uuid) to authenticated;

-- Both sides are told about an offer, the same way they are told about a
-- request and a decision. A figure nobody sees is a figure nobody answers.
create or replace function public.notify_refund_offer()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_row package_cancellations%rowtype; v_to uuid; v_from text;
begin
  select * into v_row from package_cancellations where id = new.request_id;
  if v_row.id is null then return new; end if;
  v_to := case when new.offered_by = v_row.client_id then v_row.coach_id else v_row.client_id end;
  select name into v_from from users where id = new.offered_by;

  insert into notifications (user_id, type, title, body)
  values (v_to, 'booking'::notif_type,
          coalesce(v_from, 'They') || ' offered $' || (new.amount_cents / 100)::text || ' back',
          coalesce(new.note, 'Accept it, or counter with your own figure.'));
  return new;
end $function$;

drop trigger if exists trg_notify_refund_offer on public.package_refund_offers;
create trigger trg_notify_refund_offer
  after insert on public.package_refund_offers
  for each row execute function public.notify_refund_offer();

-- A pack is frozen while a cancellation is open, not only once approved. The
-- unused count is what any offer is argued over, and booking more sessions
-- underneath it changes the thing being negotiated.
create or replace function public.package_is_cancelled(p_client uuid, p_coach uuid, p_package uuid)
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $function$
  select exists (
    select 1 from package_cancellations r
     where r.client_id = p_client and r.coach_id = p_coach
       and r.package_id = p_package
       and r.status in ('approved', 'requested', 'offered')
  );
$function$;

revoke execute on function public.package_is_cancelled(uuid, uuid, uuid) from public, anon;
grant execute on function public.package_is_cancelled(uuid, uuid, uuid) to authenticated;

-- Applied live 21 September 2026 and verified as two real signed-in accounts in
-- a rolled-back transaction:
--   coach offers 12000                       -> ok, client notified
--   coach offers again, unanswered           -> refused
--   coach accepts their own offer            -> refused
--   client counters 15000                    -> ok, coach notified
--   client books while it is open            -> refused
--   coach accepts                            -> approved at 15000, 2 offers kept
--   offering on a settled request            -> refused
--   accepting with nothing on the table      -> refused
--   a stranger offering                      -> refused
--   a stranger reading the offers            -> 0 rows
--
-- Two bugs the live checks found, both fixed above and neither visible to a
-- structural check: the ambiguous `id`, and offers tying on created_at.
